/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2016-02-17 09:57:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/menu/menu.jsp", Long.valueOf(1455698146621L));
    _jspx_dependants.put("/menu/header.jsp", Long.valueOf(1455698146621L));
    _jspx_dependants.put("/menu/footer.jsp", Long.valueOf(1455698146621L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	String ses[] = session.getValueNames();
	
	for(int le=0;le<ses.length;le++){
		if(ses[le].equals("type")){
			if(session.getAttribute("type").equals("c")){
				response.sendRedirect("cindex.jsp");
			}
			else if(session.getAttribute("type").equals("a")){
				response.sendRedirect("aindex.jsp");
			}
		}
	}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t\t<meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t\t<title>Home Page</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/validationEngine.jquery.css\" type=\"text/css\" media=\"screen\" title=\"no title\" charset=\"utf-8\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"images/Refresh.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script src=\"js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"js/jquery.validationEngine-en.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"js/jquery.validationEngine.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\t\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$(\"#formID\").validationEngine()\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- wrap starts here -->\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\t");
      out.write("<div id=\"header\">\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<h1 id=\"logo-text\">ON<span class=\"gray\">line</span></h1>\t\t\r\n");
      out.write("\t\t\t<h2 id=\"slogan\">Change Your Life ... </h2>\t\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("<div id=\"menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("</div>");
      out.write("\t\r\n");
      out.write("\t<div id=\"content-wrap\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- write your code here -->\r\n");
      out.write("\t\t<div id=\"main\">\r\n");
      out.write("\t\t\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <center>\r\n");
      out.write("\t\t");

			String msg="";
			msg = request.getParameter("msg");
			if(msg!=null)
				out.println("<br>"+msg);
		
      out.write("\r\n");
      out.write("\t\t<BR><BR>\r\n");
      out.write("\t\t<form id=\"formID\" method=\"get\" action=\"logcheck.jsp\">\r\n");
      out.write("        <table width=\"350px\" border=\"0\">\r\n");
      out.write("        <tr height=\"60px\">\r\n");
      out.write("        <td width=\"136\" align=\"center\"> User Name:\r\n");
      out.write("        \t</td>\r\n");
      out.write("\t\t\t<td width=\"152\"><input class=\"validate[required,custom[noSpecialCaracters],length[0,20],ajax[ajaxUser]]\" type=\"text\" name=\"user\" id=\"user\" /></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr height=\"60px\"><td width=\"136\" align=\"center\">PassWord : </td>\r\n");
      out.write("            <td>\r\n");
      out.write("\t\t\t<input class=\"validate[required,length[2,11]]\" type=\"password\" name=\"password\" id=\"firstname\" />\t\t\t</td>\r\n");
      out.write("            <tr align=\"center\" height=\"50px\">\r\n");
      out.write("            <td>\r\n");
      out.write("\t\t\t\t\t<span>User </span>\r\n");
      out.write("\t\t\t\t\t<input class=\"validate[required] radio\" type=\"radio\" name=\"type\" id=\"radio2\"  value=\"c\"/>\r\n");
      out.write("                    </td>\r\n");
      out.write("            \r\n");
      out.write("            <td>\r\n");
      out.write("            <span>Admin</span>\r\n");
      out.write("\t\t\t\t\t<input class=\"validate[required] radio\" type=\"radio\" name=\"type\"  id=\"radio1\" value=\"a\">\r\n");
      out.write("                    \r\n");
      out.write("                </td></tr>\r\n");
      out.write("             <tr height=\"60px\"><td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t<input class=\"submit\" type=\"submit\" value=\"Log In\"/>\r\n");
      out.write("            </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("        <br>\r\n");
      out.write("</center>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        \r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t&copy; 2010 <strong>ONline</strong> | \r\n");
      out.write("\t\t\tDesign by: | Jayvik.Hitesh.Dhaval\r\n");
      out.write("\t\t\tValid XHTML | \r\n");
      out.write("\t\t\tCSS\r\n");
      out.write("\t\t\t\r\n");
      out.write("   \t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<a href=\"index.jsp\">Home</a>&nbsp;|&nbsp;\r\n");
      out.write("   \t\t<a href=\"index.jsp\">Sitemap</a>&nbsp;|&nbsp;\r\n");
      out.write("\t   \t<a href=\"index.jsp\">RSS Feed</a>\r\n");
      out.write("   \t\t</p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
